//
//  Model.swift
//  ITIL4Quiz
//
//  Created by Cengizhan Tomak on 2.05.2023.
//

import Foundation

enum Language {
    case turkish
    case english
}

struct Topic {
    let title: String
    let quizzes: [Quiz]
}

struct Quiz {
    let title: String
    let questions: [Question]
}

struct Question {
    let question: String
    let answers: [String]
    let correctAnswerIndex: Int
}

let sampleTopicsTurkish: [Topic] = [
    Topic(title: "ITIL v4 Foundation - 1", quizzes: [
        Quiz(title: "Test 1", questions: [
            Question(question: "Hizmet ilişkisi aşağıdakilerden hangilerini içerir?\n\n1.Hizmet sağlama\n2.Hizmet tüketimi\n3.Hizmet ilişkisi yönetimi\n4.Hizmet seviye anlaşması", answers: ["1, 2 & 3", "2, 3 & 4", "Hepsi", "Hiçbiri"], correctAnswerIndex: 0),
            Question(question: "Bir paydaş için bir veya daha fazla çıktı tarafından mümkün kılınan sonuç ne olarak adlandırılır?", answers: ["Sonuç", "Çıktı", "Sonuç", "Amaç"], correctAnswerIndex: 0),
            Question(question: "ITIL'de tanımlanan dört boyut, organizasyonlara uygun bir odak düzeyine sahip olmalarını sağlar, böylece SVS'nin _______________________ olduğundan emin olur.", answers: ["Etkili ve Dengeli", "Dengeli ve Mükemmel", "Etkili ve Mükemmel", "Verimli ve dirençli"], correctAnswerIndex: 0),
            Question(question: "Hizmetleri alırken organizasyon hangi rolü üstlenir?", answers: ["Müşteri", "Hizmet sağlayıcı", "Kullanıcı", "Tüketici"], correctAnswerIndex: 3),
            Question(question: "ITIL rehber ilkelerinden hangisi, organizasyon kültürü ve davranışı için temel oluşturur?", answers: ["Günlük operasyonlar için stratejik karar verme", "Organizasyonu erken benimsemeye teşvik etme", "Kültürü ve davranışı iyileştirme", "IT Hizmetlerini sunmak için düzenleme"], correctAnswerIndex: 2),
            Question(question: "Terim “değer“ neyi ifade eder?", answers: ["Hizmetin değerli varlıkları", "Toplam sahiplik maliyeti", "Algılanan faydalar", "Bağlamsal bilgi"], correctAnswerIndex: 2),
            Question(question: "Cümleyi boşluğu doldurarak tamamlayın - “ITIL SVS, organizasyon için güçlü, __________, değer odaklı bir yönlendirme sağlar.“", answers: ["Gerekçelendirilmiş", "Birleşik", "İyileştirilmiş", "Doğru"], correctAnswerIndex: 1),
            Question(question: "Mobil ağa erişim en iyi şekilde hangi hizmet teklifleri bileşeni için bir örnektir?", answers: ["Ağa erişim", "Kaynaklara erişim", "Hareketlilik erişimi", "Hizmetlere erişim"], correctAnswerIndex: 1),
            Question(question: "Bir organizasyonun müşteriye değer sunmak için tasarlanmış kaynaklarının bir yapılandırması nedir?", answers: ["Değer", "Hizmet", "Ürün", "Yapılandırma"], correctAnswerIndex: 2),
            Question(question: "Hizmetleri sağlarken organizasyon hangi rolü üstlenir?", answers: ["Müşteri", "Hizmet sağlayıcı", "Tedarikçi", "Ortak"], correctAnswerIndex: 1)
        ]),
        Quiz(title: "Quiz 2", questions: [
            Question(question: "Hizmetlerin sağlanmasının yanı sıra, organizasyonun değer yaratmak için ne yapması gerekmektedir?", answers: ["Hizmet ilişkilerinde tüketiciyle iş birliği yapmak", "Hizmet tüketicilerini hizmet yaşam döngüsü boyunca yönetmek", "Tüm hizmetler için hizmet yönetim planı oluşturarak hizmetleri yönetmek", "Hizmet tüketicilerine düzenli eğitim seansları düzenlemek"], correctAnswerIndex: 0),
            Question(question: "Aşağıdakilerden hangisi, “Hizmet sağlayıcı ve hizmet tüketicinin birlikte değer yaratmak için gerçekleştirdiği ortak faaliyet” olarak adlandırılır?", answers: ["Değerin ortak yaratımı", "Fayda yönetimi", "Hizmet tüketimi", "Hizmet ilişkileri yönetimi"], correctAnswerIndex: 3),
            Question(question: "Bir hizmeti alan bir kişiye ___________ denir.", answers: ["Kullanıcı", "Tüketici", "Müşteri", "Sponsor"], correctAnswerIndex: 0),
            Question(question: "Bir çıktı aşağıdakilerden hangisi tarafından tanımlanır?", answers: ["Hizmet tarafından üretilen bir sonuç", "Tüm paydaşlar için yararlı bir çıktı", "Bir faaliyetin somut veya soyut teslimatı", "Müşterinin hizmetleri sağlamasına yardımcı olan bir faaliyet"], correctAnswerIndex: 2),
            Question(question: "Hizmet yönetiminin merkezi bileşeni nedir?", answers: ["Değerin gerçekleştirilmesi", "Hizmet bileşeni", "Hizmet", "Yapılandırma öğesi"], correctAnswerIndex: 2),
            Question(question: "Hizmet yönetiminin ve ITIL'in odak noktalarından biri, organizasyonların hizmet ilişkileri aracılığıyla tüketicileriyle nasıl ____________ olduğudur.", answers: ["Değer yaratma", "Fayda", "İş", "Stratejik amaç"], correctAnswerIndex: 0),
            Question(question: "Hizmet tüketimiyle ilgili hangi roller bulunmaktadır?", answers: ["Sağlayıcı, yönetici, sponsor", "Kullanıcı ve tüketici", "Müşteri, kullanıcı, sponsor", "Sponsor, kullanıcı ve tüketici"], correctAnswerIndex: 2),
            Question(question: "Bir tüketici, bir hizmet sağlayıcı tarafından sağlanan çıktıları alarak ne elde eder?", answers: ["Ürün", "Sonuç", "Amaç", "Çıktı"], correctAnswerIndex: 1),
            Question(question: "ITIL Hizmet değeri sisteminde tanımlanan ITIL yönetişi, organizasyonların sürekli olarak hangi yönetime hizmet etmek için aşağıdakilerden hangisiyle sürekli olarak hizaya gelmelerini sağlamak için yapılan faaliyetleri içerir?", answers: ["Olayları çözmek için organizasyon tarafından belirlenen yönlendirme", "Stratejik yönlendirme ile operasyonlar", "Hizmetleri iyileştirmek için yapılan girişimler", "Belirlenen süre içinde tamamlanması gereken işlemleri tamamlamak"], correctAnswerIndex: 1),
            Question(question: "Aşağıdakilerden hangisi, müşterilere hizmetlerin bir formunda değer sağlamak için özel bir organizasyonel yetenekler kümesi olarak adlandırılır?", answers: ["Hizmet teslimi", "Özelleşmiş yetenek", "Hizmet Yönetimi", "Hizmet değeri yönetimi"], correctAnswerIndex: 2)
        ]),
        Quiz(title: "Quiz 3", questions: [
            Question(question: "Aşağıdakilerden hangisi organizasyonu tanımlar?", answers: ["Stakeholder'ın ihtiyaçlarını karşılamak için birlikte çalışan insanlar", "Kendi fonksiyonu olan, sorumlulukları, yetkileri ve ilişkileri olan bir kişi veya grup", "Ortak bir amaca ulaşmak için bir araya gelen tüm paydaşların birleşimi", "Takım üyelerinin rollerini ve sorumluluklarını gösteren RACI şeması oluşturmak"], correctAnswerIndex: 1),
            Question(question: "Aşağıdakilerden hangisi paydaşın ”Hizmet Tüketici“ için değer örneğidir?", answers: ["Sağlanan Faydalar", "Belirlenmiş amaç", "Değerin ortak yaratımı", "Hizmet amacı"], correctAnswerIndex: 0),
            Question(question: "Hizmetler sağlayıcı tarafından sunulduğunda, aşağıdakilerden hangisi oluşturulur?", answers: ["Müşterinin işini yapmak için gereken becerileri sağlayan hizmetler", "Hizmetleri izleme ve yönetmede yardımcı olan hizmet varlıkları", "Hizmet tüketici için yeni bir kaynak veya mevcut kaynaklarını değiştirir", "Hizmet amaçlarını karşılayan gereken tüm hizmetler"], correctAnswerIndex: 2),
            Question(question: "Hizmet teklifinin içinde aşağıdakilerden hangileri bulunur?", answers: ["Fayda ve garanti", "Mal, kaynaklara erişim ve hizmet eylemleri", "Hizmetler ve Ürünler", "Hizmet işlevselliği"], correctAnswerIndex: 1),
            Question(question: "ITIL hizmet değeri sisteminin temel bileşenleri, İlkeler, yönetişim, Hizmet değeri zinciri, Uygulamalar ve _____________'dir?", answers: ["Sürekli iyileştirme", "Sürekli geliştirme", "Devamlı iyileştirme", "Toplam iyileştirme"], correctAnswerIndex: 2),
            Question(question: "ITIL Hizmet değeri sisteminin temel bileşenleri aşağıdakilerden hangileridir?\n\n1.Rehber modeli\n2.Sürekli iyileştirme\n3.Yönetişim\n4.Hükümet", answers: ["1&2", "2&3", "3&4", "1&4"], correctAnswerIndex: 3),
            Question(question: "Bir rol, hizmet tüketimi için bütçeyi kim onaylar?", answers: ["İlişki Yöneticisi", "Hizmet Yöneticisi", "Müşteri", "Sponsor"], correctAnswerIndex: 3),
            Question(question: "Holistik yaklaşımın uygulanmasını sağlamak için, ITIL dört boyutlu modeli önerir, aşağıdakilerden hangilerini içerir?", answers: ["Değerler ve aşırı süreçler", "Tedarikçilerden sağlanan malzemeler", "İnsanları yönetmek için teknikler", "Ortaklar ve Tedarikçiler"], correctAnswerIndex: 3),
            Question(question: "Hizmet sağlayıcı, hizmetlerini tüketiciye hangi şekilde sunar?", answers: ["Hizmet tüketimi", "Hizmet Teklifleri", "Ürün detayları", "Hizmet bileşenleri"], correctAnswerIndex: 1),
            Question(question: "Sürekli değişen bir ortamda, ITIL'in basit iyileştirme modeli bir organizasyonun _________________________'yi korumasına yardımcı olur.", answers: ["Çeviklik ve Esneklik", "Esneklik ve Dayanıklılık", "Tepki ve Esneklik", "Uygulanabilirlik ve Dayanıklılık"], correctAnswerIndex: 1)
        ]),
    ]),
    
    Topic(title: "ITIL v4 Foundation - 2", quizzes: [
        Quiz(title: "Quiz 4", questions: [
            Question(question: "Organizasyonel çeviklik ve direnç sağlamak, güçlü bir birleşik yönlendirme sağlamak ve herkes tarafından anlaşılan, değere odaklanan bir yönlendirme benimsemeyi kolaylaştırmak için hangisi sağlar?", answers: ["Hizmet değeri sistemi", "Hizmet değeri performansı", "Hizmet değeri reçetesi", "Hizmet değeri programı"], correctAnswerIndex: 0),
            Question(question: "Bir organizasyonun bir yetki sistem yapısı oluşturmasının yanı sıra, neye ihtiyacı vardır?", answers: ["Roller ve sorumlulukların net bir şekilde tanımlanması ve atandığı", "Hedefleri destekleyen ve uygun yetkinlik düzeyine sahip olan kültür", "Oluşturulan yapıyı işlevsel hale getiren yapı", "Her zaman uygulanabilir olan politikalar, süreçler, prosedürler"], correctAnswerIndex: 1),
            Question(question: "Bir organizasyon, ortaklar ve tedarikçi boyutunu ele almak için hangi yöntemi kullanabilir?", answers: ["Hizmet Bilgi ve yönetimi", "Hizmet sunumu ve yönetimi", "Hizmet varlıkları ve yönetimi", "Hizmet Entegrasyonu ve yönetimi"], correctAnswerIndex: 3),
            Question(question: "Aşağıdakilerden hangisi, ”ürünün veya hizmetin belirli bir ihtiyacı karşılamak için sunduğu işlevsellik” olarak adlandırılır?", answers: ["Değer", "Garanti", "Hizmet", "Fayda"], correctAnswerIndex: 3),
            Question(question: "ITIL SVS, aşağıdaki bileşenlerden hangisini içermez?", answers: ["Rehber ilkeler", "Uygulamalar", "Yönetişim", "Hizmet değeri zinciri"], correctAnswerIndex: 3),
            Question(question: "Verimliliği artırmak için aşağıdaki faaliyetlerden hangisi ortadan kaldırılmalıdır?", answers: ["İsraf edilen faaliyetler", "Değer akışı faaliyetleri", "Süreç faaliyetleri", "Atık yönetimi faaliyetleri"], correctAnswerIndex: 0),
            Question(question: "Bir organizasyonun ürün ve hizmetleri oluşturmak ve sunmak için kullandığı adımlar serisi nedir?", answers: ["Değer Yolu", "Değer Akışı", "Değer Serisi", "Değer Adımları"], correctAnswerIndex: 1),
            Question(question: "“Bir organizasyonun __________, kullanmayı tercih ettiği teknolojilere önemli etkisi olabilir”, Eksik kelimeyi doldurun.", answers: ["Değer", "Kültür", "Teknoloji", "Süreç"], correctAnswerIndex: 1),
            Question(question: "Aşağıdakilerden hangisi, ”Belirli faaliyetler ve kaynaklar için harcanan miktar” olarak adlandırılır?", answers: ["Harcama", "Hizmet Ücreti", "Maliyet", "Fiyat"], correctAnswerIndex: 2),
            Question(question: "Boyut ”organizasyon ve insan”nın ana unsuru hangisidir?", answers: ["İnsanlar", "Problem", "Süreç", "İlerleme"], correctAnswerIndex: 0)
        ]),
        Quiz(title: "Quiz 5", questions: [
            Question(question: "Aşağıdakilerden hangisi organizasyonlar arasındaki ilişkiyi içerir?", answers: ["Entegrasyon ve resmiyet", "Yorumlama ve algı", "Yatırım ve maliyetler", "Entegrasyon ve oluşum"], correctAnswerIndex: 0),
            Question(question: "Tüketicinin perspektifinden, hizmet ilişkilerinde yer alan iki tür Risk hangileridir?\n1. Hizmet tarafından tüketiciden kaldırılan risk\n2. Hizmet tarafından tüketiciye yüklenen risk\n3. Hizmet sağlanırken ortaya çıkan risk", answers: ["1 & 2", "1 & 3", "2 & 3", "Yukarıdakilerin hiçbiri"], correctAnswerIndex: 0),
            Question(question: "Değer akışları ve süreç boyutu ne ile ilgilenmektedir?", answers: ["İnsanların ve organizasyonun birlikte performansı", "Becerilerin, yetkinliklerin, değer akışı ve sürecin kurulması için nasıl kullanıldığı", "Organizasyonun farklı parçalarının entegre ve koordineli şekilde çalışması", "Hizmetleri, hizmet bileşenlerini entegre etme ve yönetme"], correctAnswerIndex: 2),
            Question(question: "Bir organizasyonun içsel değişiklikleri desteklemek için hızlı, esnek, kararlı bir şekilde hareket etme yeteneği neyi tanımlar?", answers: ["Çeviklik", "DevOps", "Waterfall", "Lean"], correctAnswerIndex: 0),
            Question(question: "Bilgi ve teknoloji boyutu neleri içerir?", answers: ["Hizmetlerin yönetimi için gerekli bilgi, bilgi ve teknoloji", "Hizmetleri izlemek ve yönetmek için bilgi ve veri işleme becerileri", "Teknoloji kaynaklarını yönetmek için gerekli bilgi ve bilgi, aynı zamanda hizmetler", "Veri ve bilginin işlenmesi için gerekli olan bilgi yönetim sistemleri"], correctAnswerIndex: 0),
            Question(question: "ITIL SVS, aşağıdaki iş yaklaşımlarını destekler, yalnızca?", answers: ["Çevik", "DevOps", "Kırılgan", "Lean"], correctAnswerIndex: 2),
            Question(question: "Bir organizasyonun her bir hizmeti ve ürünü için neyin tanımlanması gerekmektedir?", answers: ["Hizmet reçetesi", "Değer gerilemesi", "Hizmet yönetimi", "Değer akışları"], correctAnswerIndex: 3),
            Question(question: "Ortak ve tedarikçi boyutu, organizasyon arasındaki ilişkiyi içerir, hangileri bunlarla ilgilidir?", answers: ["Tasarım, Geliştirme, Departman, Teslimat, Destek, Sürekli İyileştirme","Dizayn, Geliştirme, Dağıtım, Teslimat, Destek, Sürekli İyileştirme", "Karar, Geliştirme, Dağıtım, Teslimat, Destek, Sürekli İyileştirme", "Belirleme, Geliştirme, Dağıtım, Teslimat, Destek, Sürekli İyileştirme", "Dizayn, Geliştirme, Dağıtım, Teslimat, Destek, Sürekli İyileştirme"], correctAnswerIndex: 1),
            Question(question: "Eksik kelimeyi doldurun, “Örgütsel hücrelerin parçalanmasında etkili bir yöntemdir.”", answers: ["Değer yönetim sistemi", "Hizmet teslim mekanizması", "Değere odaklanma", "Hizmet teslim yöntemi"], correctAnswerIndex: 2),
            Question(question: "SVS, tüm paydaşlarla sürekli olarak hangi araçların kullanımı ve yönetimi aracılığıyla değer ortaya çıkarır?", answers: ["Projeler ve hizmetler", "Ürünler ve projeler", "Ürünler ve hizmetler", "Projeler ve yönetim"], correctAnswerIndex: 2)
        ]),
        Quiz(title: "Quiz 6", questions: [
            Question(question: "Aşağıdaki sorular hangileri bilgi ve teknoloji boyutu için organizasyonun dikkate alması gereken sorulardır?\n1. Hangi bilgiler hizmetler tarafından yönetilmektedir?\n2. Hizmetleri sunmak ve yönetmek için hangi destekleyici bilgi ve bilgi gereklidir?\n3. Bilgi ve bilgi varlıkları nasıl korunacak, yönetilecek, arşivlenecek ve bertaraf edilecektir?", answers: ["Yalnızca 1", "2 ve 3", "Hepsi", "Hiçbiri"], correctAnswerIndex: 2),
            Question(question: "Hizmet sağlayıcılar eylemlerini bir vakumda gerçekleştirmezler. Aşağıdaki faktörlerden hangilerinden etkilenirler?", answers: ["Politik, Çevresel, Yerel, Sosyal, Teknolojik, ekonomik", "Politik, Çevresel, Yasal, Sosyal, Teknolojik, ekonomik", "Politik, Çevresel, Yasal, Tedarik, Teknolojik, ekonomik", "Politik, Çevresel, Yasal, Sosyal, Teknolojik, ergonomik"], correctAnswerIndex: 1),
            Question(question: "ITIL, hizmet yönetimine bütünsel yaklaşımı desteklemek için neyi tanımlar?", answers: ["Organizasyonel hedefler", "Hizmet değeri ortak oluşturma", "Hizmetin dört boyutu", "Hizmetin tüm boyutları"], correctAnswerIndex: 2),
            Question(question: "Bir organizasyonun içsel ve dışsal uygulamalardan kaynaklanan aşamalı değişikliklere ve ani kesintilere nasıl tepki vereceği, nasıl hazırlık yapacağı, nasıl yanıt vereceği ve nasıl adapte olacağını tanımlayan nedir?", answers: ["Organizasyonel çözünürlük", "Organizasyonel direnç", "Organizasyonel direnç", "Organizasyonel restore"], correctAnswerIndex: 2),
            Question(question: "Aşağıdakilerden hangisi, “Zarar veya kayba neden olabilecek veya hedeflere ulaşmayı zorlaştırabilecek olası bir olay” olarak adlandırılır?", answers: ["Olay", "Risk", "Sorun", "Problem"], correctAnswerIndex: 1),
            Question(question: "Desteklediği teknolojiler aşağıdakileri içerir, ancak bunlarla sınırlı değildir?\n\n1. İş akışı yönetim sistemleri\n2. Bilgi tabanları\n3. Veritabanı yönetim sistemi\n4. İletişim sistemleri", answers: ["1, 2 ve 3", "2, 3 ve 4", "1, 3 ve 4", "1, 2 ve 4"], correctAnswerIndex: 3),
            Question(question: "Tüketici perspektifinden, hizmet ilişkilerinde yer alan maliyetler hangi iki türdür?\n\n1. Hizmet tarafından tüketiciden kaldırılan maliyet\n2. Hizmet sağlanırken ortaya çıkan maliyet\n3. Hizmet tarafından tüketiciye yüklenen maliyet", answers: ["1 ve 2", "1 ve 3", "2 ve 3", "Yukarıdakilerin hiçbiri"], correctAnswerIndex: 1),
            Question(question: "Hizmet sağlayıcı, riskleri hangi kişi adına yönetir?", answers: ["Tüketici", "Sponsor", "Tedarikçi", "Ortak"], correctAnswerIndex: 0),
            Question(question: "“Anlaşmaya uygun olarak ürünün veya hizmetin karşılayacağı güvence”, buna ne denir?", answers: ["Fayda", "Garanti", "Değer", "Yarar"], correctAnswerIndex: 1),
            Question(question: "Süreç terimi aşağıdakilerden hangisinde iyi tanımlanmıştır?", answers: ["Girdileri çıktılara dönüştüren bir dizi ilişkili veya etkileşen faaliyet", "Girdileri üretimden sonra geri bildirim alan bir dizi eylem", "Amaçlarını gerçekleştiren bir dizi açıklama", "Hizmet yönetiminden önce tamamlanması gereken bir dizi eylem öğesi"], correctAnswerIndex: 0)
        ]),
    ]),
    
    Topic(title: "ITIL v4 Foundation - 3", quizzes: [
        Quiz(title: "Quiz 7", questions: [
            Question(question: "Önerilen bir prensip, bir organizasyona, hedeflerinde, stratejilerinde, çalışma türünde veya yönetim yapısında değişiklik olmasına bakılmaksızın tüm durumlarda rehberlik eden nedir?", answers: ["Uygulamalar", "Yönetişim", "Rehber İlke", "Hizmet değer zinciri"], correctAnswerIndex: 2),
            Question(question: "Bireylerin ve ekiplerin davranışlarıyla birlikte yapısal nedenlerle de meydana gelebilen nedir?", answers: ["Kademeler", "Yapı", "Silolar", "Hizmet"], correctAnswerIndex: 2),
            Question(question: "ITIL SVS içindeki faaliyetleri tetikleyen nedir ve bu faaliyetler değer yaratmaya yol açar?", answers: ["Fırsat ve Fayda", "Fırsat ve Talep", "Fayda ve Garanti", "Talep ve Garanti"], correctAnswerIndex: 1),
            Question(question: "DevOps olarak bilinen şeyin evriminde neyin itici faktörlerinden biri olmuştur?", answers: ["Hizmetin ve hizmet yönetiminin temsil edilmesi her zaman", "Gerçek işbirliği ihtiyacının tanınması", "Hizmet ilişki yönetiminin düzenlenmesi", "Genel işbirliği ihtiyacının tanınması"], correctAnswerIndex: 1),
            Question(question: "İyileştirme faaliyeti sessizlik içinde veya sadece küçük bir grup ayrıntıları farkında olduğunda ne ön plana çıkabilir?", answers: ["Varsayımlar ve yanıtlar", "Varsayımlar ve söylentiler", "Açıklama ve tanıma", "Arbitraj ve Tartışmalar"], correctAnswerIndex: 1),
            Question(question: "Her şeyi aynı anda yapmaya çalışma ilkesi hangisinde belirtilmiştir?", answers: ["Bulunduğunuz yerden başlayın", "Değere odaklanın", "Geri bildirimle aşamalı ilerleyin", "Basit ve pratik olun"], correctAnswerIndex: 2),
            Question(question: "Yönetişimin gerçekleştirilmesi hangi aşamalarla gerçekleşir?", answers: ["Değerlendirme, Yönlendirme ve İzleme", "Etkileşim, Yönlendirme ve İzleme", "Değerlendirme, Yönlendirme ve Denetim", "Değerlendirme, Yönlendirme ve Yönetim"], correctAnswerIndex: 2),
            Question(question: "Bir faaliyetin çıktısının bir kısmının yeni girdi için kullanıldığı durumu ifade etmek için yaygın olarak kullanılan terim nedir?", answers: ["Geri bildirim", "İleriye yönelik girdi", "Çözünürlük", "Yanıt"], correctAnswerIndex: 0),
            Question(question: "Boşluğu doldurun, “İşbirliği ve işbirliği _________ çalışmaktan daha iyidir”?", answers: ["Bireysel", "Artımsal", "Önemli", "İzole"], correctAnswerIndex: 3),
            Question(question: "İlk ve en açık paydaş grubu nedir?", answers: ["Tedarikçi", "Ekip üyeleri", "Sponsor", "Müşteri"], correctAnswerIndex: 3)
        ]),
        Quiz(title: "Quiz 8", questions: [
            Question(question: "Aşağıdakilerden hangisi, “mevcut olanı dikkate almadan sıfırdan başlamayın ve yeni bir şey inşa etmeye çalışmayın” ilkesine vurgu yapar?", answers: ["Bulunduğunuz yerden başlayın", "Değere odaklanın", "Geri bildirimle aşamalı ilerleyin", "Basit ve pratik olun"], correctAnswerIndex: 0),
            Question(question: "Bir uygulama, süreç, hizmet, ölçüm veya diğer iyileştirme hedefi analiz edilirken her zaman ne sorulmalıdır?", answers: ["Değer onayını tamamlar mı?", "Değer yaratmayı tehlikeye atar mı?", "Değer yaratmaya katkıda bulunur mu?", "Değer onayına katkıda bulunur mu?"], correctAnswerIndex: 2),
            Question(question: "Bir organizasyonun hizmet üzerinde bir bütün olarak çalışma ihtiyacı hangi ilkenin içinde belirtilir?", answers: ["Bulunduğunuz yerden başlayın", "Holistik düşünün ve çalışın", "Geri bildirimle aşamalı ilerleyin", "Basit ve pratik olun"], correctAnswerIndex: 1),
            Question(question: "Müşterinin ürün ve hizmete olan ihtiyacı veya isteği aşağıdakilerden hangisiyle temsil edilir?", answers: ["Talep", "Değer", "Sonuç", "Fırsat"], correctAnswerIndex: 0),
            Question(question: "Paydaşların iş yükünün ve çalışmanın ilerlemesinin düşük görünürlüğü olduğunda aşağıdakilerden hangi risk meydana gelir?", answers: ["Çalışmanın öncelik olmadığı izlenimini yaratma", "Çalışmanın öncelikli olduğu izlenimini yaratma", "Çalışmanın önceliğinin engellenmesi", "Çalışmanın öncelikli olamayacağı izlenimi yaratma"], correctAnswerIndex: 0),
            Question(question: "Paydaşlara değer katmak için seçenekler ve olasılıklar aşağıdakilerden hangisiyle temsil edilir?", answers: ["Talep", "Değer", "Sonuç", "Fırsat"], correctAnswerIndex: 3),
            Question(question: "Gözlemlenenlerin analizini desteklemek için ne kullanılır?", answers: ["Yönetim", "Ölçüm", "Analitik", "Değerlendirme"], correctAnswerIndex: 1),
            Question(question: "Otomasyon düşünülürken önemli olan nedir?", answers: ["Optimizasyon ve Tavsiye", "Düzenleme ve Karmaşıklık", "Düzenleme ve Tavsiye", "Optimizasyon ve Basitleştirme"], correctAnswerIndex: 3),
            Question(question: "Personel üyeleri değişimin ne olduğunu ve nasıl etkileyebileceğini speküle ettiğinde ne ortaya çıkabilir?", answers: ["Değişime direnç", "Zorluğa direnç", "Değişimi çözme", "Zorluğa çözüm"], correctAnswerIndex: 0),
            Question(question: "“Gerçekten gereksiz olan her şeyi ortadan kaldırın ve teknolojiyi yapabileceği her şeyi başarmak için kullanın” ilkesi hangisinde belirtilmiştir?", answers: ["Bulunduğunuz yerden başlayın", "Holistik düşünün ve çalışın", "Optimize edin ve Otomatikleştirin", "Basit ve pratik olun"], correctAnswerIndex: 2)
        ]),
        Quiz(title: "Quiz 9", questions: [
            Question(question: "Hangi ilkeye göre, organizasyon her zaman sonuçlar elde eden pratik çözümler üretmek için sonuç odaklı düşünmeyi kullanmalıdır?", answers: ["Bulunduğunuz yerden başlayın", "Holistik düşünün ve çalışın", "İlerleme ve geri besleme ile yavaş yavaş ilerleyin", "Basit ve pratik olun"], correctAnswerIndex: 3),
            Question(question: "Geri bildirim döngüleriyle gömülü bir şekilde zaman sınırlı bir iteratif şekilde çalışmak, aşağıdakilerden hangisine izin verir?\n\n1. Daha fazla esneklik\n2. Müşteri ve iş gereksinimlerine daha hızlı yanıtlar\n3. Başarısızlığı hızlı bir şekilde keşfetme ve yanıtlama yeteneği\n4. Genel kalitenin iyileştirilmesi", answers: ["1, 2 & 3", "2, 3 & 4", "Hepsi", "Hiçbiri"], correctAnswerIndex: 2),
            Question(question: "Bir şeyi ihtiyaç duyulduğu kadar etkili ve yararlı hale getirmek ne anlama gelir?", answers: ["Düzenlilik", "Optimizasyon", "Azaltma", "Onaylama"], correctAnswerIndex: 1),
            Question(question: "Değer odaklılık ilkesi aşağıdakileri kapsar?", answers: ["Müşterilerin ve kullanıcıların uzmanlığı da dahil olmak üzere birçok perspektifi", "Müşterilerin ve kullanıcıların deneyimi de dahil olmak üzere birçok perspektifi", "Müşterilerin ve kullanıcıların maruz kalma olasılığı da dahil olmak üzere birçok perspektifi", "Müşterilerin ve kullanıcıların deneyimi de dahil olmak üzere birçok olasılığı"], correctAnswerIndex: 3),
            Question(question: "Aşağıdakilerden hangisi “işbirliği yapmak ve görünürlüğü teşvik etmek” ilkesini temsil eder?", answers: ["Sınırları aşarak birlikte çalışmak, daha fazla satın alma, hedeflere daha fazla ilgi ve uzun vadeli başarı olasılığını artırır.", "Sınırları aşarak birlikte çalışmak, daha fazla kontrol, engellere daha fazla ilgi ve kısa vadeli başarı olasılığını artırır.", "Sınırları aşarak birlikte çalışmak, daha fazla satın alma, engellere daha fazla ilgi ve kısa vadeli başarı olasılığını artırır.", "Sınırları aşarak birlikte çalışmak, daha fazla kontrol, hedeflere daha fazla ilgi ve uzun vadeli başarı olasılığını artırır."], correctAnswerIndex: 0),
            Question(question: "Holistik bir yaklaşım, organizasyonun tüm bileşenlerinin entegre bir şekilde nasıl çalıştığını anlamayı içerir.", answers: ["Yönetim", "Ölçüm", "Analitik", "Değerlendirme"], correctAnswerIndex: 0),
            Question(question: "Bir organizasyonun yönlendirildiği ve kontrol edildiği bir sistem hangisidir?", answers: ["Yönetişim", "Yönetim", "Denetleme", "Liderlik"], correctAnswerIndex: 0),
            Question(question: "Hangi ilkeye göre, her zaman bir hedefi gerçekleştirmek için minimum adım sayısını kullanmalısınız?", answers: ["Bulunduğunuz yerden başlayın", "Holistik düşünün ve çalışın", "Optimizasyon ve Otomatikleştirme", "Basit ve pratik olun"], correctAnswerIndex: 3),
            Question(question: "Hizmetler, iç ve dış hizmet tüketicilere aşağıdakilerin koordinasyonu ve entegrasyonu ile sunulur?", answers: ["Hizmet yönetimi prensipleri", "Yönetimin holistik yaklaşımı", "Hizmet yönetiminin dört boyutu", "Dış ve iç faktörler"], correctAnswerIndex: 2),
            Question(question: "Organizasyonların, insan ve teknik kaynaklarının yaptığı işin değerini ________. Boşluğu doldurun.", answers: ["Azaltmak", "En üst düzeye çıkarmak", "Optimize etmek", "Düzenlemek"], correctAnswerIndex: 3)
        ]),
    ]),
    
    Topic(title: "ITIL v4 Foundation - 4", quizzes: [
        Quiz(title: "Quiz 10", questions: [
            Question(question: "Kapasite ve performans yönetiminin amacı nedir?", answers: ["Hizmet kapasitesini her zaman iş kapasitesine eşit tutmak", "Hizmet kapasitesinin hizmet garantisi ve hizmet özelliklerini belirlemeye odaklanmasını sağlamak", "Hizmet performansını hizmet bileşenlerinin kapasitesiyle uyumlu hale getirmek", "Hizmetlerin anlaşılabilir ve beklenen performansı sağlayarak mevcut ve gelecekteki talepleri maliyet etkin bir şekilde karşılamak"], correctAnswerIndex: 3),
            Question(question: "Hizmet yönetimi ve ITSM endüstrisinde hangi yönetim uygulamaları geliştirilmiştir?", answers: ["Hizmet Yönetimi Uygulamaları", "Teknik Yönetim Uygulamaları", "Destek Yönetimi Uygulamaları", "Genel Yönetim Uygulamaları"], correctAnswerIndex: 0),
            Question(question: "Metrik olarak toplanan veriler genellikle hangi şekilde sunulur?", answers: ["Raporlar veya sunumlar", "E-posta formu ve Gösterge panelleri", "Raporlar veya Gösterge panelleri", "E-posta formu ve Raporlar"], correctAnswerIndex: 2),
            Question(question: "Bir organizasyonun sürekli sürdürülebilirliğini ve müşterileri için değer yaratmayı sağlamak için hangisinin yönetimi önemlidir?", answers: ["Kaynak", "İnsanlar", "Risk", "Teknoloji"], correctAnswerIndex: 2),
            Question(question: "İşletme yenilikçilik ve farklılaşmada başarı faktörlerinden biri nedir?", answers: ["Pazar Odaklılık", "Pazarın Spesifikasyonu", "Pazarın Özgünlüğü", "Hızlı Pazarlama"], correctAnswerIndex: 3),
            Question(question: "Problem aşağıdakilerden hangisiyle en iyi şekilde tanımlanabilir?", answers: ["Tekrarlayan olayların nedeni", "Hizmetleri kesintiye uğratan birçok olayın nedeni", "Bir veya daha fazla olayın nedeni veya potansiyel nedeni", "Tasarımdaki bir kusur nedeniyle meydana gelen bir olay"], correctAnswerIndex: 2),
            Question(question: "Risk yönetiminin etkinliği için hangileri dikkate alınmalıdır?", answers: ["Riskin Tanımlanması, Değerlendirilmesi ve Tedavisi", "Riskin Asimilasyonu, Değerlendirilmesi ve Çevirisi", "Entegrasyon, Değerlendirme ve Çeviri Riski", "Riskin Tanımlanması, Açıklanması ve Tedavisi"], correctAnswerIndex: 3),
            Question(question: "Organizasyonda tüm projelerin başarıyla tamamlanmasını sağlayan hangi uygulama sorumludur?", answers: ["Bilgi Yönetimi", "İlişki Yönetimi", "Portföy Yönetimi", "Proje Yönetimi"], correctAnswerIndex: 3),
            Question(question: "Hizmet yönetimine genel iş yönetimi alanlarından hangileri uyarlanmış ve benimsenmiştir?", answers: ["Hizmet Yönetimi Uygulamaları", "Teknik Yönetim Uygulamaları", "Destek Yönetimi Uygulamaları", "Genel Yönetim Uygulamaları"], correctAnswerIndex: 3),
            Question(question: "“Strateji yönetimi, organizasyonun yönelimini belirler, çabaları odaklandırır, öncelikleri tanımlar veya açıklar ve ortamın yanıtında tutarlılık veya rehberlik sağlar.” İfadeleri doğru mu yanlış mıdır?", answers: ["Doğru", "Yanlış", "", ""], correctAnswerIndex: 0)
        ]),
        Quiz(title: "Quiz 11", questions: [
            Question(question: "Organizasyon kaynak stratejisi aşağıdakileri içerir?", answers: ["İç kaynak temini, Dış kaynak temini, Çoklu kaynak temini", "İç kaynak temini, Dış kaynak temini, Çoklu lokasyon kaynak temini", "İç kaynak temini, Dış kaynak temini, Çoklu kaynak temini", "İç kaynak temini, Dış kaynak temini, Çoklu kaynak temini"], correctAnswerIndex: 3),
            Question(question: "Gerekli güvenlik aşağıdaki arasında bir denge sağlamalıdır?", answers: ["Önleme, Açıklama ve Düzeltme", "Reçeteleme, Tespit ve Düzeltme", "Önleme, Yön ve Düzeltme", "Önleme, Tespit ve Düzeltme"], correctAnswerIndex: 3),
            Question(question: "Aşağıdakilerden hangisi Uygulama'nın doğru tanımıdır?", answers: ["Bir işi gerçekleştirmek veya bir hedefi tamamlamak için tasarlanmış kurumsal uygulamaların bir seti.", "Bir işi gerçekleştirmek veya bir hedefi tamamlamak için tasarlanmış kurumsal kaynakların bir seti.", "Bir işi gerçekleştirmek veya bir hedefi tamamlamak için tasarlanmış kurumsal süreçlerin bir seti.", "Bir işi gerçekleştirmek veya bir hedefi tamamlamak için tasarlanmış kurumsal portföylerin bir seti."], correctAnswerIndex: 1),
            Question(question: "IT varlık yönetimi uygulamasının amacı aşağıdakilerden hangisi için tüm IT varlıklarının tam yaşam döngüsünü planlamak ve yönetmektir?", answers: ["Sınırlı, 2, 3 ve 4", "Sadece 2, 3, 4 ve 5", "Hepsi", "Hiçbiri"], correctAnswerIndex: 2),
            Question(question: "ITIL sürekli iyileştirme modeli aşağıdakilerden hangisi olarak kullanılabilir?", answers: ["İyileştirme girişimlerini desteklemek için bir rehber", "Müşteri katılımı iyileştirme modeli olarak uygulanabilir", "Kullanıcı yönetim sistemini iyileştirmek için bir rehber", "Hizmetler boyunca yönetim için bir model"], correctAnswerIndex: 0),
            Question(question: "Bir hizmetin veya başka bir yapılandırma öğesinin yönetimi için önemli olan herhangi bir durum değişikliği aşağıdakilerden hangisi olarak adlandırılır?", answers: ["Olay", "Olay", "Hata", "Değişiklik"], correctAnswerIndex: 1),
            Question(question: "Girdileri çıktılara dönüştürmek için değer zinciri faaliyetleri aşağıdaki hangi kombinasyonu kullanır?", answers: ["Portföy", "Faaliyetler", "Uygulamalar", "Süreçler"], correctAnswerIndex: 2),
            Question(question: "Aşağıdaki sürekli hizmet iyileştirme modelinde eksik olan adımı belirleyin. Vizyon nedir? Şu anda neredeyiz? Nereye gitmek istiyoruz? Nasıl oraya gideriz? __________________ Oraya ulaştık mı? __________________", answers: ["Aksiyon al ve momentumu nasıl sürdüreceğimizi belirle", "Aksiyon al ve momentumu nasıl sürdüreceğimizi belirle", "Aktivite yap ve momentumu nasıl sürdüreceğimizi belirle", "Aksiyon al ve momentumu nasıl sürdüreceğimizi belirle"], correctAnswerIndex: 3),
            Question(question: "ITIL hizmet değer zinciri, aşağıdaki altı değer zinciri faaliyetinden hangilerini içerir ve bunlar ürünlerin ve hizmetlerin oluşturulmasına ve sonuçta değere yol açar?", answers: ["Planla, dahil et, ilişkilendir, tasarla ve geçir, elde et/oluştur, sun ve destekle", "Planla, iyileştir, ilişkilendir, tasarla ve dönüştür, elde et/oluştur, sun ve destekle", "Planla, iyileştir, ilişkilendir, tasarla ve dönüştür, elde et/oluştur, karar ver ve destekle", "Planla, iyileştir, ilişkilendir, tasarla ve geçir, elde et/oluştur, sun ve destekle"], correctAnswerIndex: 3),
            Question(question: "Bir IT hizmetinin veya başka bir yapılandırma öğesinin gerektiğinde anlaşmaya varılan işlevini yerine getirme yeteneği aşağıdakilerden hangisi olarak tanımlanır?", answers: ["Süreklilik", "Güvenilirlik", "Kullanılabilirlik", "Kapasite"], correctAnswerIndex: 2)
        ]),
        Quiz(title: "Quiz 12", questions: [
            Question(question: "Taleplere yanıt vermek ve ürün ve hizmetlerin oluşturulması ve yönetimi yoluyla değer gerçekleştirmeyi kolaylaştırmak için gerekli temel faaliyetleri belirleyen işletme modeline ne ad verilir?", answers: ["Hizmet Değer Zinciri", "Hizmet Değer Sistemi", "Hizmet Doğrulama Sistemi", "Hizmet Değer Kanalı"], correctAnswerIndex: 1),
            Question(question: "Bilginin belirli bir bağlamda kullanıldığı durumu ifade etmek için hangi terim kullanılır?", answers: ["Bilgi", "Bilgi", "Bağlamsal bilgi", "Bilgilendirilmiş eylem"], correctAnswerIndex: 0),
            Question(question: "Aşağıdaki uygulamaların amacı, belirsizlik düzeyini azaltarak iyi karar verme ve sürekli iyileştirmeyi desteklemektir?", answers: ["Bilgi Yönetimi", "Ölçüm ve Raporlama", "Proje Yönetimi", "İlişki Yönetimi"], correctAnswerIndex: 1),
            Question(question: "Teknoloji yönetimi alanlarından hangi yönetim uygulamaları hizmet yönetimi amaçları için benimsenmiştir?", answers: ["Hizmet Yönetimi Uygulamaları", "Teknik Yönetim Uygulamaları", "Destek Yönetimi Uygulamaları", "Genel Yönetim Uygulamaları"], correctAnswerIndex: 1),
            Question(question: "Aşağıdaki uygulamaların hangisinin amacı, sürekli iyileştirmeyi sağlamak için organizasyon uygulamalarını ve hizmetleri değişen iş ihtiyaçlarıyla uyumlu hale getirmektir?", answers: ["İlişki Yönetimi Uygulaması", "Sürekli İyileştirme Uygulaması", "Risk Yönetimi Uygulaması", "Bilgi Güvenliği Yönetimi Uygulaması"], correctAnswerIndex: 1),
            Question(question: "Hizmet değer akışları ve belirli bir senaryo için tasarlanan kombinasyon aşağıdakilerin hangisini gösterir?", answers: ["Faaliyetler ve programlar", "Faaliyetler ve uygulamalar", "Faaliyetler ve süreçler", "Uygulamalar ve Süreçler"], correctAnswerIndex: 1),
            Question(question: "Hizmet sağlayıcının tüm uygulamalarını etkileyen teslimat türü aşağıdakilerden hangisidir?", answers: ["Yüksek Hızlı", "Düşük Hızlı", "Çok Yüksek Hızlı", "Ortalama Hızlı"], correctAnswerIndex: 0),
            Question(question: "Başarılı bir tedarik stratejisi için aşağıdakilerin tam anlamıyla anlaşılması gerekmektedir?", answers: ["Bir organizasyonun hedefleri, sağlamak ve desteklemek için gereken kaynaklar, çevresel (örneğin pazar) faktörler ve belirli yaklaşımları yönetme riskleri.", "Bir organizasyonun hedefleri, stratejiyi sağlamak için gereken kaynaklar, çevresel (örneğin pazar) faktörler ve belirli yaklaşımların uygulanmasıyla ilişkili riskler.", "Bir organizasyonun hedefleri, stratejiyi sağlamak için gereken insanlar, çevresel (örneğin pazar) faktörler ve belirli yaklaşımların uygulanmasıyla ilişkili riskler.", "Bir organizasyonun yönü, stratejiyi sağlamak için gereken kaynaklar, çevresel (örneğin pazar) faktörler ve belirli yaklaşımlarla yönetilen ve uygulanan riskler."], correctAnswerIndex: 1),
            Question(question: "Aşağıdaki uygulamalardan hangisinin amacı, risklerin uygun şekilde değerlendirildiğinden emin olarak başarılı IT değişikliklerinin sayısını en üst düzeye çıkarmak, değişikliklerin devam etmesine izin vermek ve değişiklik programını yönetmektir?", answers: ["Değişiklik Yönetimi", "Yayın Yönetimi", "Değişiklik Kontrolü", "Dağıtım Yönetimi"], correctAnswerIndex: 2),
            Question(question: "Aşağıdaki uygulamalardan hangisinin amacı, organizasyonun genel stratejisini destekleyen programlar, projeler, hizmetler ve ürünlerin doğru karışımına sahip olduğundan emin olmaktır?", answers: ["Bilgi Yönetimi", "İlişki Yönetimi", "Portföy Yönetimi", "Proje Yönetimi"], correctAnswerIndex: 2)
        ]),
    ]),
]

let sampleTopicsEnglish: [Topic] = [
    Topic(title: "ITIL v4 Foundation - 1", quizzes: [
        Quiz(title: "Quiz 1", questions: [
            Question(question: "Service relationship includes which of the following?\n\n1.Service provision\n2.Service consumption\n3.Service relationship management\n4.Service level agreement", answers: ["1, 2 & 3", "2, 3 & 4", "All of the above", "None of the above"], correctAnswerIndex: 0),
            Question(question: "What is called as, “a result for a stakeholder enabled by one or more outputs”?", answers: ["Outcome", "Output", "Result", "Objective"], correctAnswerIndex: 0),
            Question(question: "The four-dimensions defined in ITIL helps organizations have an appropriate amount of focus, so that organization ensures that the SVS remains, _______________________", answers: ["Effective and Balanced", "Balanced and Excellent", "Effective and Excellent", "Efficient and resilient"], correctAnswerIndex: 0),
            Question(question: "What role does the organization take while receiving the services", answers: ["Client", "Service provider", "User", "Consumer"], correctAnswerIndex: 3),
            Question(question: "Which among the following from the ITIL guiding principles creates the foundation for organization culture and behaviour?", answers: ["Strategic decision making for day to day operations", "Motivating organization for early adoption", "Improving the culture and behaviour", "Organizing for delivering the IT Services"], correctAnswerIndex: 2),
            Question(question: "What does the term value refers to?", answers: ["Valuable assets of service", "Total cost of ownership", "Perceived Benefits", "Contextual knowledge"], correctAnswerIndex: 2),
            Question(question: "Complete the sentence by filling the blank – “The ITIL SVS facilitates the integration and coordination and provides a strong, __________, value-focused direction for the organization”", answers: ["Justified", "Unified", "Improved", "Straight"], correctAnswerIndex: 1),
            Question(question: "Access to mobile network is the best example for which component of service offerings?", answers: ["Access to network", "Access to resources", "Access to mobility", "Access to services"], correctAnswerIndex: 1),
            Question(question: "What is “A configuration of an organizations resources designed to offer value to costumer”?", answers: ["Value", "Service", "Product", "Configuration"], correctAnswerIndex: 2),
            Question(question: "What role does the organization take while provisioning the services", answers: ["Customer", "Service Provider", "Supplier", "Partner"], correctAnswerIndex: 1)
        ]),
        Quiz(title: "Quiz 2", questions: [
            Question(question: "To create value, what should the organization do other than providing services?", answers: ["Cooperate with the consumers in the service relationships", "Manage service consumers throughout the services lifecycle", "Create the service management plan for all the services, so that services are managed", "Conduct regular training session to service consumers"], correctAnswerIndex: 0),
            Question(question: "What is called as, “The joint activity performed by service provider and service consumer to co-create value”?", answers: ["Co-creation of value", "Benefit management", "Service consumption", "Service Relationship management"], correctAnswerIndex: 3),
            Question(question: "A person who receives a service is called as ___________.", answers: ["User", "Consumer", "Customer", "Sponsor"], correctAnswerIndex: 0),
            Question(question: "An output is defined by which of the following?", answers: ["An outcome produced by a service", "An output which is useful to the all stakeholders", "A tangible or intangible deliverable of an activity", "An activity which helps customer to provision the services"], correctAnswerIndex: 2),
            Question(question: "What is the central component of the service management?", answers: ["Value realization", "Service component", "Service", "Configuration item"], correctAnswerIndex: 2),
            Question(question: "A key focus of service management, and of ITIL, is the way that organizations _____________ with their consumers through service relationships", answers: ["Co-create value", "Benefit", "Business", "Strategic objective"], correctAnswerIndex: 0),
            Question(question: "What are the roles involved in service consumption?", answers: ["Provider, manager, sponsor", "User & consumer", "Customer, user, sponsor", "Sponsor, User & Consumer"], correctAnswerIndex: 2),
            Question(question: "What would a consumer achieve by receiving the outputs produced by the services provided by a services provider?", answers: ["Product", "Outcome", "Objective", "Output"], correctAnswerIndex: 1),
            Question(question: "The ITIL governance defined in ITIL Service value system, includes the activities to enable organizations to continually align to, which of the following?", answers: ["Direction set by organization to resolve incidents", "Operations with strategic direction set by governing body", "Initiatives taken to improve services", "Complete the actions to complete with in the defined timelines"], correctAnswerIndex: 1),
            Question(question: "What is called as, a set of specialized organizational capabilities for enabling the value for customers in the form of services?", answers: ["Service delivery", "Specialized capability", "Service Management", "Service value management"], correctAnswerIndex: 2)
        ]),
        Quiz(title: "Quiz 3", questions: [
            Question(question: "Which of the following define the organization?", answers: ["The people working together to accomplish the needs of a stakeholder", "A person or group of people that has its own function with responsibilities, authorities and relationships to achieve the objectives", "A conglomeration of all the stakeholders working together to achieve the common cause", "Establishing a RACI chart to depict the roles and responsibilities of all the team members"], correctAnswerIndex: 1),
            Question(question: "Which of the following is the example of value for the stakeholder’ “Service Consumer”?", answers: ["Benefits Achieved", "Defined objective", "Value co-creation", "Service objective"], correctAnswerIndex: 0),
            Question(question: "When services are delivered by the provider, they create which of the following?", answers: ["Services that provide the skills needed for customer to their business", "Service assets which helps in monitoring and managing services", "New resource for service consumer or modifies their existing ones", "All the required services, which fulfils the service objectives"], correctAnswerIndex: 2),
            Question(question: "Which of the following is included in the service offering?", answers: ["Utility and warranty", "Goods, access to resources and service actions", "Services and Products", "Service functionalities"], correctAnswerIndex: 1),
            Question(question: "The core components of ITIL service value systems are Principles, governance, Service value chain, Practices and _____________?", answers: ["Continuous improving", "Always improvement", "Continual Improvement", "Total Improvement"], correctAnswerIndex: 2),
            Question(question: "Which of the following are the key components of the ITIL Service value system?\n\n1.Guiding principles\n2.Review model\n3.Continual improvement\n4.Government", answers: ["1&2", "2&3", "3&4", "1&4"], correctAnswerIndex: 3),
            Question(question: "Which role authorises the budget for service consumption?", answers: ["Relationship Manager", "Service Manager", "Customer", "Sponsor"], correctAnswerIndex: 3),
            Question(question: "To ensure the application of holistic approach, ITIL recommends the four-dimensional model, which includes, which of the following?", answers: ["Values and extreme processes", "Supply from suppliers", "Techniques to manage people", "Partners & Suppliers"], correctAnswerIndex: 3),
            Question(question: "Service provider presents their services to consumer in what form?", answers: ["Service consumption", "Service Offerings", "Product details", "Service components"], correctAnswerIndex: 1),
            Question(question: "In a constantly changing environment, the ITIL’s simple improvement model helps to maintain an organization’s, _________________________", answers: ["Agility and Flexibility", "Resilience and Agility", "Response and Flexibility", "Applicability and Resilience"], correctAnswerIndex: 1)
        ]),
    ]),
    
    Topic(title: "ITIL v4 Foundation - 2", quizzes: [
        Quiz(title: "Quiz 4", questions: [
            Question(question: "What provides the means to achieve organizational agility and resilience and to facilitate the adoption of a strong unified direction, focused on value and understood by everyone in the organization?", answers: ["Service value system", "Service value performance", "Service value prescription", "Service value program"], correctAnswerIndex: 0),
            Question(question: "What does an organization need in addition to establishing a structure for system of authority?", answers: ["The roles and responsibilities clearly defined and assigned", "The culture that supports the objectives and right level of competencies", "The structure that makes the established structure function", "The policies, processes, procedures which are applicable always"], correctAnswerIndex: 1),
            Question(question: "Which one of the methods may an organization use to address the partners and supplier dimension?", answers: ["Service Information and management", "Service delivery and management", "Service assets and management", "Service Integration and management"], correctAnswerIndex: 3),
            Question(question: "What is called as, “The functionality offered by the product or services to meet the particular need?", answers: ["Value", "Warranty", "Service", "Utility"], correctAnswerIndex: 3),
            Question(question: "ITIL SVS includes which of the following components except?", answers: ["Guiding principles", "Practices", "Governance", "Service value channel"], correctAnswerIndex: 3),
            Question(question: "Which of the following activities has to be eliminated to increase productivity?", answers: ["Wasteful activities", "Value stream activities", "Process activities", "Waste management activities"], correctAnswerIndex: 0),
            Question(question: "What is the series of steps that an organization uses to create and deliver products and services called?", answers: ["Value Strom", "Value Stream", "Value Series", "Value Steps"], correctAnswerIndex: 1),
            Question(question: "“The __________ of an organization may have the significant impact on the technologies it chooses to use”, Fill the missing word.", answers: ["Value", "Culture", "Technology", "Process"], correctAnswerIndex: 1),
            Question(question: "What is called as, “The amount of money spent on specific activities and resources”?", answers: ["Expenditure", "Service Fee", "Cost", "Price"], correctAnswerIndex: 2),
            Question(question: "Which is the key element of the dimension “organization and people”?", answers: ["People", "Problem", "Process", "Progress"], correctAnswerIndex: 0)
        ]),
        Quiz(title: "Quiz 5", questions: [
            Question(question: "Which of the following does the relationship between organizations involve?", answers: ["Integration and formality", "Interpretation and perception", "Investment and costs", "Integration and formation"], correctAnswerIndex: 0),
            Question(question: "From the consumer perspective what are the two types of Risks involved in service relationships?\n1.Risk removed from the consumer by the service\n2.Risk imposed on the consumer by the service\n3.Risk occurred while provisioning the service", answers: ["1 & 2", "1 & 3", "2 & 3", "None of the above"], correctAnswerIndex: 0),
            Question(question: "What is it that the value streams & process dimension is concerned with?", answers: ["Performance of the people and organization together", "How well the skills, capabilities are utilized to establish the value stream and process", "How the various parts of the organization work in integrated and coordinated way", "Integration of services, service components to monitor and manage them"], correctAnswerIndex: 2),
            Question(question: "What defines the ability of an organization to move and adopt quickly, flexibly, decisively to support internal changes?", answers: ["Agile", "DevOps", "Water Fall", "Lean"], correctAnswerIndex: 0),
            Question(question: "What does the information and technology dimension include?", answers: ["Information, knowledge and technology necessary for management of services", "Information and data processing skills to monitor and manage the services", "Information and knowledge required to management the technology resources, as well as services", "Information management systems essential for processing the data and information"], correctAnswerIndex: 0),
            Question(question: "ITIL SVS support many work approaches, except?", answers: ["Agile", "DevOps", "Fragile", "Lean"], correctAnswerIndex: 2),
            Question(question: "What needs to be defined by an organization for each of their services and products?", answers: ["Service prescription", "Value retardation", "Service management", "Value streams"], correctAnswerIndex: 3),
            Question(question: "The partner and supplier dimension encompasses the relationship between the organization, that are involved in which of the following?", answers: ["Design, Development, Department, Delivery, Support, Continual Improvement", "Design, Development, Deployment, Delivery, Support, Continual Improvement", "Decide, Development, Deployment, Delivery, Support, Continual Improvement", "Design, Development, Deployment, Delivery, Support, Continual Important"], correctAnswerIndex: 1),
            Question(question: "Fill the missing word, “Promoting a _____________ is an effective method of breaking down organization silo.”", answers: ["Value management system", "Service delivery mechanism", "Focus on value creation", "Service delivery method"], correctAnswerIndex: 2),
            Question(question: "SVS co-create the value continually with all stakeholders through the use and management of which of the following?", answers: ["Projects and services", "Products and projects", "Products and services", "Projects and management"], correctAnswerIndex: 2)
        ]),
        Quiz(title: "Quiz 6", questions: [
            Question(question: "Which of the following questions should the organization consider for information & technology dimension?\n1. What information is managed by the services?\n2. What supporting information and knowledge are needed to deliver and manage the services?\n3. How will the information and knowledge assets be protected, managed, archived, and disposed of?", answers: ["1 Only", "2 & 3", "All", "None"], correctAnswerIndex: 2),
            Question(question: "Service providers do not perform their action in a vacuum. They are influenced by which of the following factors?", answers: ["Political, Environmental, Local, Social, Technological, economical", "Political, Environmental, Legal, Social, Technological, economical", "Political, Environmental, Legal, Supply, Technological, economical", "Political, Environmental, Legal, Social, Technological, ergonomics"], correctAnswerIndex: 1),
            Question(question: "ITIL defines what to support the holistic approach to service management?", answers: ["Organizational objectives", "Service value co-creation", "Four Dimensions of the service", "All dimension of the service"], correctAnswerIndex: 2),
            Question(question: "What defines the ability of the organization to anticipate, prepare for, respond to, and adopt to both incremental changes and sudden disruptions from internal and external practice.", answers: ["Organizational resolution", "Organizational resistance", "Organizational resilience", "Organizational restoration"], correctAnswerIndex: 2),
            Question(question: "What is called as, “A possible event that could cause harm or loss, or make it more difficult to achieve objectives”?", answers: ["Incident", "Event", "Risk", "Problem"], correctAnswerIndex: 1),
            Question(question: "The technologies that support include, but are not limited to, which of the following?\n\n1. Workflow management systems\n2. Knowledge bases\n3. Database management system\n4. Communication systems", answers: ["1, 2 & 3", "2, 3 & 4", "1, 3 & 4", "1, 2 & 4"], correctAnswerIndex: 3),
            Question(question: "From the consumer perspective what are the two types of costs involved in service relationships?\n\n1. Cost removed from the consumer by the service\n2. Cost incurred while provisioning the service\n3. Cost imposed to the consumer by the service", answers: ["1 & 2", "1 & 3", "2 & 3", "None of the above"], correctAnswerIndex: 1),
            Question(question: "On behalf of whom does the service provider manage risks?", answers: ["Consumer", "Sponsor", "Supplier", "Partner"], correctAnswerIndex: 0),
            Question(question: "“An assurance that the product or service will meet agreed requirements”, is called as?", answers: ["Utility", "Warranty", "Value", "Benefit"], correctAnswerIndex: 1),
            Question(question: "The term process is well defined in which of the following?", answers: ["A set of interrelated or interacting activities that transforms inputs into outputs", "A set of actions which obtain feedback after producing inputs", "A sequence of articulation that achieves its objectives", "A sequence of action items which are to be completed before service management"], correctAnswerIndex: 0)
        ]),
    ]),
    
    Topic(title: "ITIL v4 Foundation - 3", quizzes: [
        Quiz(title: "Quiz 7", questions: [
            Question(question: "A recommendation that guides an organization in all circumstances, regardless of changes in its goals, strategies, type of work, or management structure, is called as?", answers: ["Practices", "Governance", "Guiding Principle", "Service value chain"], correctAnswerIndex: 2),
            Question(question: "What can occur through the behaviour of individuals and teams, but also through structural causes?", answers: ["Strata", "Structure", "Silos", "Service"], correctAnswerIndex: 2),
            Question(question: "What triggers activities within the ITIL SVS, and these activities lead to the creation of value?", answers: ["Opportunity & Utility", "Opportunity & Demand", "Utility & Warranty", "Demand & Warranty"], correctAnswerIndex: 1),
            Question(question: "What has been one of the driving factors in the evolution of what is known as DevOps?", answers: ["Representation of the service and service management always", "Recognition of the need of genuine collaboration", "Regularization of the service relationship management", "Recognition of the need of general collaboration"], correctAnswerIndex: 1),
            Question(question: "What can prevail when improvement activity occurs in relative silence, or with only a small group being aware of the details?", answers: ["Assumptions and responses", "Assumptions and rumours", "Articulation and recognition", "Arbitration and Arguments"], correctAnswerIndex: 1),
            Question(question: "Do not attempt to do everything at once is mentioned by which principle?", answers: ["Start where you are", "Focus on value", "Progress iteratively with feedback", "Keep it simple and practical"], correctAnswerIndex: 2),
            Question(question: "Realization of the governance happens through which of the following?", answers: ["Evaluate, Divert and Monitor", "Engage, Direct and Monitor", "Evaluate, Direct and Monitor", "Evaluate, Direct and Master"], correctAnswerIndex: 2),
            Question(question: "What is the term commonly used to refer the situation part of the output of an activity used for new input?", answers: ["Feedback", "Forwarded input", "Resolution", "Response"], correctAnswerIndex: 0),
            Question(question: "Fill in the blank, “Cooperation and collaboration are better than __________ work”?", answers: ["Individual", "Incremental", "important", "Isolated"], correctAnswerIndex: 3),
            Question(question: "What is the first and most obvious stakeholder group?", answers: ["Supplier", "Team members", "Sponsor", "Customer"], correctAnswerIndex: 3)
        ]),
        Quiz(title: "Quiz 8", questions: [
            Question(question: "Which principle stresses on, “do not start from scratch and build something new without considering what is already available to be leveraged”?", answers: ["Start where you are", "Focus on value", "Progress iteratively with feedback", "Keep it simple and practical"], correctAnswerIndex: 0),
            Question(question: "When analysing a practice, process, service, metric, or other improvement target, what should always be asked?", answers: ["Whether it complements the value confirmation", "Whether it compromises the value creation", "Whether it contributes to value creation", "Whether it contributes to value confirmation"], correctAnswerIndex: 2),
            Question(question: "The need of organization to work on the service as a whole is mentioned in which of the following principles", answers: ["Start where you are", "Think and work holistically", "Progress iteratively with feedback", "Keep it simple and practical"], correctAnswerIndex: 1),
            Question(question: "The need or desire for product & services from customer is represented by which of the following?", answers: ["Demand", "Value", "Outcome", "Opportunity"], correctAnswerIndex: 0),
            Question(question: "When stakeholders have poor visibility of the workload and progression of work, there is a risk of which of the following?", answers: ["Creating the impression that work is not a priority", "Creating the impression that work is a priority", "Creating the impediment that work is not a priority", "Creating the impossibility that work is a priority"], correctAnswerIndex: 0),
            Question(question: "Options and possibilities to add value to stakeholders is represented by which of the following?", answers: ["Demand", "Value", "Outcome", "Opportunity"], correctAnswerIndex: 3),
            Question(question: "What is used to support the analysis of what has been observed?", answers: ["Management", "Measurement", "Analytics", "Assessment"], correctAnswerIndex: 1),
            Question(question: "While considering for automation, what is important?", answers: ["Optimization & Recommendation", "Organizing & Complexity", "Organizing & Recommendation", "Optimization & Simplifying"], correctAnswerIndex: 3),
            Question(question: "What will arise as the staff members speculate about what is changing and how it might impact them?", answers: ["Resistance to Change", "Resistance to Challenge", "Resolution to Change", "Resolution to Challenge"], correctAnswerIndex: 0),
            Question(question: "“Eliminate anything that is truly wasteful and use technology to achieve whatever it is capable of” is mentioned in which of the following principles", answers: ["Start where you are", "Think and work holistically", "Optimize and Automate", "Keep it simple and practical"], correctAnswerIndex: 2)
        ]),
        Quiz(title: "Quiz 9", questions: [
            Question(question: "According to which principle, organization should always use outcome-based thinking to produce practical solutions that deliver results?", answers: ["Start where you are", "Think and work holistically", "Progress iteratively with feedback", "Keep it simple and practical"], correctAnswerIndex: 3),
            Question(question: "Working in a timeboxed iterative manner with feedback loops embedded into the process allows for which of the following?\n\n1. Greater flexibility\n2. Faster responses to customer and business needs\n3. The ability to discover & respond to the failure quickly\n4. The overall improvement of the quality", answers: ["1, 2 & 3", "2, 3 & 4", "All of the above", "None of the above"], correctAnswerIndex: 2),
            Question(question: "What does it mean to make something as effective and useful as it needs to be?", answers: ["Regularization", "Optimization", "Reduction", "Confirmation"], correctAnswerIndex: 1),
            Question(question: "The principle focus on value encompasses which of the following?", answers: ["Many prescriptions, including the expertise of the customers and users", "Many prospectuses, including the experience of the customers and users", "Many probabilities, including the exposure of the customers and users", "Many perspectives, including the experience of the customers and users"], correctAnswerIndex: 3),
            Question(question: "Which of the following represents the principles “collaborate and promote visibility”", answers: ["Working together across boundaries produces results that have greater buy-in, more relevance to objectives, and increased likelihood of long-term success.", "Working together across borders produces results that have greater check-in, more relevance to objectives, and increased likelihood of long-term success.", "Working together across borders produces results that have greater buy-in, more relevance to obstacles, and increased likelihood of short-term success.", "Working together across boundaries produces results that have greater check-in, more relevance to obstacles, and increased likelihood of short-term success."], correctAnswerIndex: 0),
            Question(question: "Taking the holistic approach to service management includes, which of the following?", answers: ["Establishing an understanding of how all parts of organization work together in integrated way", "Establishing the holistic process which fit for all the practices", "Establishing the integrated progress group which works together to accomplish all the objectives", "Establishing the information management system which is enabled by automation and machine learning"], correctAnswerIndex: 0),
            Question(question: "What is a system by which an organization is directed and controlled?", answers: ["Governance", "Management", "Supervision", "Leading"], correctAnswerIndex: 0),
            Question(question: "According to which principle, always use the minimum number of steps to accomplish an objective?", answers: ["Start where you are", "Think and work holistically", "Optimize and Automate", "Keep it simple and practical"], correctAnswerIndex: 3),
            Question(question: "Services are delivered to internal and external service consumers through the coordination and integration of which of the following?", answers: ["Service management principles", "The holistic approach of management", "The four dimensions of service management", "The external and internal factors"], correctAnswerIndex: 2),
            Question(question: "Organizations must ________ the value of the work carried out by their human and technical Resources. Fill in the blank.", answers: ["Minimise", "Maximise", "Optimize", "Organize"], correctAnswerIndex: 3)
        ]),
    ]),
    
    Topic(title: "ITIL v4 Foundation - 4", quizzes: [
        Quiz(title: "Quiz 10", questions: [
            Question(question: "What is the purpose of capacity and performance management?", answers: ["To ensure service capacity remains equal to business capacity always", "To ensure service capacity focuses on establishing the warranty of the services and achieve service attributes", "To ensure service performance is aligned with the capacity of the service components", "To ensure that services achieve agreed and expected performance, satisfying current and future demands in a cost-effective way."], correctAnswerIndex: 3),
            Question(question: "What management practices have been developed in service management and ITSM industry?", answers: ["Service Management Practices", "Technical Management Practices", "Support Management Practices", "General Management Practices"], correctAnswerIndex: 0),
            Question(question: "Data collected as metrics are usually presented in which form?", answers: ["Reports or presentations", "Email form & Dashboards", "Reports or Dashboards", "Email form & Reports"], correctAnswerIndex: 2),
            Question(question: "Managing what, is essential to ensuring the ongoing sustainability of an organization and creating value for its customers", answers: ["Resource", "People", "Risk", "Technology"], correctAnswerIndex: 2),
            Question(question: "In business innovation and differentiation, what is a key success factor?", answers: ["Specialization to Market", "Specification of Market", "Speciality of Market", "Speed to Market"], correctAnswerIndex: 3),
            Question(question: "Problem can be best defined by which of the following?", answers: ["A cause of repetitive incidents", "A cause of many incidents interrupts the services", "A cause, or potential cause, of one or more incidents", "An incident caused by the defect in the design"], correctAnswerIndex: 2),
            Question(question: "For effectiveness of risk management, it has to consider which of the following?", answers: ["Identification, Assessment & Treatment of Risk", "Identification, Assimilation & Treatment of Risk", "Integration, Assessment & Translation of Risk", "Identification, Articulation & Treatment of Risk"], correctAnswerIndex: 3),
            Question(question: "Which practice ensures that all the projects in the organization are successfully delivered?", answers: ["Knowledge Management", "Relationship Management", "Portfolio Management", "Project Management"], correctAnswerIndex: 3),
            Question(question: "What management practices have been adopted and adapted for service management from general business management domains?", answers: ["Service Management Practices", "Technical Management Practices", "Support Management Practices", "General Management Practices"], correctAnswerIndex: 3),
            Question(question: "“Strategy management establishes the organization’s direction, focuses effort, defines or clarifies the organization’s priorities, and provides consistency or guidance in response to the environment”, Is the statement true or false?", answers: ["True", "False", "", ""], correctAnswerIndex: 0)
        ]),
        Quiz(title: "Quiz 11", questions: [
            Question(question: "The organization sourcing strategy includes which of the following?", answers: ["Inside sourcing, Outsourcing, Multi-sourcing", "In-sourcing, Outsourcing, Multi location sourcing", "In-sourcing, external sourcing, Multi-sourcing", "In-sourcing, Outsourcing, Multi-sourcing"], correctAnswerIndex: 3),
            Question(question: "The required security is established by means of policies, processes, behaviours, risk management, and controls, which must maintain a balance between which of the following?", answers: ["Prevention, Description & Correction", "Prescription, Detection & Correction", "Prevention, Direction & Correction", "Prevention, Detection & Correction"], correctAnswerIndex: 3),
            Question(question: "Which of the following is the correct definition of the Practice?", answers: ["A set of organizational practices designed for performing work or accomplishing an objective.", "A set of organizational resources designed for performing work or accomplishing an objective.", "A set of organizational processes designed for performing work or accomplishing an objective.", "A set of organizational portfolios designed for performing work or accomplishing an objective."], correctAnswerIndex: 1),
            Question(question: "The purpose of the IT asset management practice is to plan and manage the full lifecycle of all IT assets, to help the organization for which of the following? maximize value control costs manage risks support decision-making about purchase, re-use, and retirement of assets meet regulatory and contractual requirements.", answers: ["Only 1, 2, 3 & 4", "Only 2, 3, 4 & 5", "All of the above", "None of the above"], correctAnswerIndex: 2),
            Question(question: "The ITIL continual improvement model can be used as which of the following?", answers: ["Guide to support improvement initiatives", "Model to implement for customer engagement improvement", "Guide for improving the user management system", "Model to manage throughout the services"], correctAnswerIndex: 0),
            Question(question: "Any change of state that has significance for the management of a service or other configuration item (CI), is called as?", answers: ["Incident", "Event", "Error", "Change"], correctAnswerIndex: 1),
            Question(question: "To convert inputs into outputs, the value chain activities use different combination of which of the following?", answers: ["Portfolio", "Activities", "Practices", "Processes"], correctAnswerIndex: 2),
            Question(question: "Identify the missing step in the below continual service improvement model. What is the vision? Where are we now? Where do we want to be? How do we get there? __________________ Did we Get there? __________________", answers: ["Try action and How do we complete the momentum going", "Take action and How do we complete the momentum going", "Take activity and How do we keep the momentum going", "Take action and How do we keep the momentum going"], correctAnswerIndex: 3),
            Question(question: "The ITIL service value chain includes, which of the following six value chain activities, which lead to the creation of products and services and, in turn, value", answers: ["Plan, involve, engage, design & transition, obtain/build, deliver & support", "Plan, improve, engage, design & transform, obtain/bold, deliver & support", "Plan, improve, engage, design & transform, obtain/build, decide & support", "Plan, improve, engage, design & transition, obtain/build, deliver & support"], correctAnswerIndex: 3),
            Question(question: "The ability of an IT service or other configuration item to perform its agreed function when required, is defined as?", answers: ["Continuity", "Reliability", "Availability", "Capacity"], correctAnswerIndex: 2)
        ]),
        Quiz(title: "Quiz 12", questions: [
            Question(question: "An operating model which outlines the key activities required to respond to demand and facilitate value realization through the creation and management of products and services is called as?", answers: ["Service Value System", "Service Value Chain", "Service Verification System", "Service Value Channel"], correctAnswerIndex: 1),
            Question(question: "What term does it refer to, when the information is used in certain context?", answers: ["Knowledge", "Information", "Contextual information", "Informed action"], correctAnswerIndex: 0),
            Question(question: "The purpose of which practices is to support good decision-making and continual improvement by decreasing the level of uncertainties?", answers: ["Knowledge Management", "Measurement & Reporting", "Project Management", "Relationship Management"], correctAnswerIndex: 1),
            Question(question: "What management practices have been adopted from technology management domains for service management purposes.", answers: ["Service Management Practices", "Technical Management Practices", "Support Management Practices", "General Management Practices"], correctAnswerIndex: 1),
            Question(question: "The purpose of which of the following practice is to align organization practices and services with changing business needs through the ongoing identification and improvement of services, service components etc.?", answers: ["Relationship Management Practice", "Continual Improvement Practice", "Risk Management Practice", "Information Security Management Practice"], correctAnswerIndex: 1),
            Question(question: "Service value streams and specific combination of which of the following, shows that each one is designed for a particular scenario?", answers: ["Activities & programs", "Activities & practices", "Activities & processes", "Practices & Processes"], correctAnswerIndex: 1),
            Question(question: "What type of delivery influences all the practices of service provider?", answers: ["High Velocity", "Low Velocity", "Very High Velocity", "Average Velocity"], correctAnswerIndex: 0),
            Question(question: "A successful sourcing strategy requires a thorough understanding of which of the following?", answers: ["An organization’s objectives, the resources required to deliver and support, the environmental (e.g. market) factors, and the risks associated with managing specific approaches.", "An organization’s objectives, the resources required to deliver that strategy, the environmental (e.g. market) factors, and the risks associated with implementing specific approaches.", "An organization’s objectives, the people required to deliver & support, the environmental (e.g. market) factors, and the risks associated with implementing specific approaches.", "An organization’s direction, the resources required to deliver that strategy, the environmental (e.g. market) considerations, and the risks managed and implemented during specific approaches."], correctAnswerIndex: 1),
            Question(question: "Which practice has the purpose to maximize the number of successful IT changes by ensuring that risks have been properly assessed, authorizing changes to proceed, and managing the change schedule.", answers: ["Change Management", "Release Management", "Change Control", "Deployment Management"], correctAnswerIndex: 2),
            Question(question: "The purpose of which practice is to ensure that the organization has right mix of programs, projects, services & products that support organization’s strategy as a whole?", answers: ["Knowledge Management", "Relationship Management", "Portfolio Management", "Project Management"], correctAnswerIndex: 2)
        ]),
    ]),
]
